blank_issues_enabled: false
contact_links:
  - name: ğŸ“š å…ˆçœ‹å¸¸è§é—®é¢˜
    url: https://maresoft365.github.io/pkg-hub-official-website/
    about: å¤§éƒ¨åˆ†åŸºç¡€é—®é¢˜éƒ½èƒ½åœ¨è¿™é‡Œæ‰¾åˆ°ç­”æ¡ˆï¼
  - name: ğŸ’¬ äº¤æµåé¦ˆï¼ˆéBugï¼‰
    url: https://github.com/Maresoft365/pkg-hub/discussions
    about: ä½¿ç”¨å’¨è¯¢ã€åŠŸèƒ½å»ºè®®ç­‰éBugç±»é—®é¢˜ï¼Œæ¬¢è¿å»Discussionsæ¿å—ï½
